node.name: ecommerce-logstash
api.environment: dev
http.host: "0.0.0.0"
xpack.monitoring.enabled: true
# path.config: /usr/share/logstash/config/logstash.conf
path.logs: /logs
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]