version: "3.9"
services:
  ecommerce-postgres:
    image: postgres
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5
    container_name: ecommerce-pgdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ecommerce-pgdata:/var/lib/postgresql/data
  ecommerce-pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce-pgadmin4-container
    restart: always
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ecommerce-pgadmin-data:/var/lib/pgadmin
  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app-container
    ports:
      - "8085:8080"
    depends_on:
      - ecommerce-postgres
    volumes:
      - ecommerce-app-logs:/app/logs
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - "85:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    

volumes:
  ecommerce-pgdata:
  ecommerce-pgadmin-data:
  ecommerce-app-logs: